name: test-site-caldwell
favicon: null
layout_spectrum: 0.59166
typography_spectrum: 0.68993
title: test-site-caldwell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6875
  lightness: 0.8541934518143535
  saturation: 0.4375
  rhythmicContrast: 0.3827596129849553
purpose: []
